#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
# source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
# source "$PLUGIN_CORE_AVAILABLE_PATH/config/functions"

APP="$1";

# echo $APP

HOOKS_DIR=${HOOKS_DIR:-hooks}

run_hook() {
    local hook_name="$1"
    if [ -f "$HOOKS_DIR/$hook_name" ]; then
        if [ ! -x "$HOOKS_DIR/$hook_name" ]; then
            chmod +x "$HOOKS_DIR/$hook_name"
        fi
        "$HOOKS_DIR/$hook_name"
    fi
}
