#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/config/functions"

APP="$1";

HOOKS_DIR=${HOOKS_DIR:-./hooks}

if [ -f "$HOOKS_DIR/post-deploy" ]; then
    if [ ! -x "$HOOKS_DIR/post-deploy" ]; then
        chmod u+x $HOOKS_DIR/post-deploy
    fi
     $HOOKS_DIR/post-deploy
fi