#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/config/functions"

APP="$1";

HOOKS_DIR=${HOOKS_DIR:-./hooks}

dokku run $APP node dist/server.js