#!/usr/bin/env python3

import subprocess
import sys

APP= sys.argv[1] if len(sys.argv) >1 else None

def pip_install(dependancy):
    try:
        subprocess.check_call(["pip3", "install", dependancy])
    except subprocess.CalledProcessError:
         print("Failed to install '{dependancy}'")

if __name__ == "__main__":
    pip_install("pymongo")
    pip_install("python-dotenv")